### ISSUE TITLE
Доделать тестовое задание

### ISSUE THREAD

**Issue by Kasiwadzaki** [basmingo/lines-to-groups-parser#1]
Привет, меня зовут Вадим, я разработчик компании BaltInfoCom.  
У тебя не совсем корректно выполнено тестовое задание. У нас должна быть возможность указывать имя файла при запуске программы, а у тебя имя файла захардкожено, а так же мы по окончанию программмы должны получать файл. Об этом написано в тестовом задании

**Comment by basmingo** [comment]
Привет, обновил. Теперь при запуске указывается абсолютный путь к input файлу, результат выводится в папку с .jar

**Comment by Kasiwadzaki** [comment]
@basmingo Отревьюил и есть пара моментов:
 - Нет обработки если файл в аргументах отсутсвует или если ошибки парса, надо добавить обработку и понятный ексепшн 
 - Валидаторе ты парсишь long, но при этом числа могут быть с плавающей точкой, нужно учесть этот момент
 - tempList объявлен как филд, но в этом нет необходимости, его можно сделать локальной переменной
 - printToFile можно сделать статическим методом, необязательно создавать лишний объект ResultHandler
 - В printTofFile надо убрать e.printStackTrace() и добавить выброс эксепшена
 - Так же запусти вот этот файл после всех правок на своем коде и скажи сколько у тебя получилось и за какое время https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

**Comment by basmingo** [comment]
@Kasiwadzaki Привет, прошло много времени, но я переписал большую часть программы:

* lng-big.csv выдает 105036 строк. Скорость выполнения - 5 секунд. 
* Добился гораздо более высокой производительности.
* Убрал регулярные выражения для ускорения, парсинг чисел с плавающей запятой сделал умножением на 100, чтобы хранить Long вместо String и потреблять меньше памяти
* Сделал статическим методом печать файла
* Добавил обработку случаев с несуществующим путем до файла, добавил обработку если файл не указан
* Вместо e.printStackTrace() выбрасывается новое исключение. Учитываю возможную нецелесообразность создания нового исключения для единственного случая. Но решил не выбрасывать чистый RuntimeException.
* Провел рефакторинг, код теперь должен читаться легче
